BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "android_metadata" (
	"locale"	TEXT
);
CREATE TABLE IF NOT EXISTS "MESSAGEMACRO2" (
	"AID"	INTEGER,
	"uid"	TEXT,
	"conAssetUid"	TEXT,
	"MACROASSETNAME"	VARCHAR,
	"MACROTYPE"	INTEGER,
	"SMS_TEL"	VARCHAR,
	"MODIDATE"	VARCHAR,
	"USEYN"	VARCHAR,
	"APP_PACKAGE"	VARCHAR,
	"APP_NAME"	VARCHAR,
	"ORDERSEQ"	INTEGER,
	"utime"	real,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("AID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "INOUTCOME" (
	"AID"	INTEGER,
	"uid"	TEXT,
	"assetUid"	TEXT,
	"CARDDIVIDMONTH"	VARCHAR,
	"ctgUid"	TEXT,
	"toAssetUid"	TEXT,
	"ZCONTENT"	VARCHAR,
	"ZDATE"	VARCHAR,
	"WDATE"	VARCHAR,
	"DO_TYPE"	VARCHAR,
	"ZMONEY"	VARCHAR,
	"txUidTrans"	TEXT,
	"ZDATA"	VARCHAR,
	"SMS_RDATE"	VARCHAR,
	"IN_ZMONEY"	VARCHAR,
	"ASSET_NIC"	VARCHAR,
	"CATEGORY_NAME"	VARCHAR,
	"cardDivideUid"	TEXT,
	"CARD_DIVIDE_MONTH_STR"	VARCHAR,
	"MARK"	INTEGER,
	"txUidFee"	TEXT,
	"SMS_ORIGIN"	VARCHAR,
	"SMS_PARSE_CONTENT"	VARCHAR,
	"IS_DEL"	INTEGER,
	"UTIME"	INTEGER,
	"currencyUid"	TEXT,
	"AMOUNT_ACCOUNT"	REAL,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("AID")
);
CREATE TABLE IF NOT EXISTS "ASSETS" (
	"ID"	integer,
	"CARD_DAY_FIN"	varchar,
	"CARD_DAY_PAY"	varchar,
	"NIC_NAME"	varchar,
	"ORDERSEQ"	integer,
	"ZDATA"	varchar,
	"ZDATA1"	varchar,
	"ZDATA2"	varchar,
	"IS_TRANS_EXPENSE"	INTEGER,
	"IS_CARD_AUTO_PAY"	INTEGER,
	"APP_PACKAGE"	varchar,
	"APP_NAME"	varchar,
	"SMS_TEL"	varchar,
	"SMS_STRING"	varchar,
	"A_UTIME"	INTEGER,
	"CARD_USAGE_HURDLE_TYPE"	integer,
	"CARD_USAGE_HURDLE_START_DATE"	real,
	"CARD_USAGE_HURDLE_AMOUNT"	real,
	"uid"	TEXT,
	"currencyUid"	TEXT,
	"cardAssetUid"	TEXT,
	"groupUid"	TEXT,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ZCATEGORY" (
	"ID"	integer,
	"C_IS_DEL"	integer,
	"C_UTIME"	INTEGER,
	"uid"	TEXT,
	"NAME"	varchar,
	"ORDERSEQ"	integer,
	"TYPE"	integer,
	"STATUS"	integer,
	"pUid"	TEXT,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ZETC" (
	"Z_PK"	integer,
	"uid"	TEXT,
	"E_UTIME"	INTEGER,
	"ZDATATYPE"	integer,
	"ZDATA"	varchar,
	"ZZDATA"	varchar,
	"ZZDATA1"	varchar,
	"ZZDATA2"	varchar,
	"dataTypeKey"	varchar,
	"isDel"	integer,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("Z_PK" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "REPEATTRANSACTION" (
	"DEVICE_ID"	INTEGER,
	"uid"	TEXT,
	"IS_DEL"	INTEGER,
	"USETIME"	INTEGER,
	"MARK"	INTEGER,
	"END_DATE"	INTEGER,
	"NEXT_DATE"	INTEGER,
	"DO_TYPE"	INTEGER,
	"REPEAT_TYPE"	INTEGER,
	"assetUid"	TEXT,
	"toAssetUid"	TEXT,
	"ctgUid"	TEXT,
	"currencyUid"	TEXT,
	"AMOUNT_SUB"	REAL,
	"MEMO"	VARCHAR,
	"PAYEE"	VARCHAR,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("DEVICE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FAVTRANSACTION" (
	"DEVICE_ID"	INTEGER,
	"uid"	TEXT,
	"IS_DEL"	INTEGER,
	"USETIME"	INTEGER,
	"MARK"	INTEGER,
	"DO_TYPE"	INTEGER,
	"assetUid"	TEXT,
	"toAssetUid"	TEXT,
	"ctgUid"	TEXT,
	"AMOUNT_SUB"	REAL,
	"currencyUid"	INTEGER,
	"MEMO"	VARCHAR,
	"PAYEE"	VARCHAR,
	"ORDERSEQ"	INTEGER,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("DEVICE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ASSETGROUP" (
	"DEVICE_ID"	INTEGER,
	"uid"	TEXT,
	"IS_DEL"	INTEGER,
	"USETIME"	INTEGER,
	"ACC_GROUP_NAME"	VARCHAR,
	"TYPE"	INTEGER,
	"ORDERSEQ"	INTEGER,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("DEVICE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SMS_RAW_READ" (
	"ID"	integer,
	"uid"	TEXT,
	"RDATE"	varchar,
	"ZDATE"	integer,
	"TEL"	varchar,
	"ZDATA"	varchar,
	"MACROTYPE"	integer,
	"assetUid"	TEXT,
	"toAssetUid"	TEXT,
	"NOTIFY_TYPE"	integer,
	"AMOUNT"	varchar,
	"TEXT_PARSING_TIME"	integer,
	"ASSETNAME"	varchar,
	"TYPE"	varchar,
	"MMSID"	integer,
	"APP_PACKAGE"	varchar,
	"APP_NAME"	varchar,
	"SENDER_NAME"	varchar,
	"IS_DEL"	integer,
	"utime"	real,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PHOTO" (
	"DEVICE_ID"	INTEGER,
	"uid"	TEXT,
	"IS_DEL"	INTEGER,
	"USETIME"	INTEGER,
	"txUid"	TEXT,
	"FILE_SIZE"	INTEGER,
	"FILE_PATH"	VARCHAR,
	"FILE_NAME"	VARCHAR,
	"ORG_FILE_NAME"	VARCHAR,
	"ORG_FILE_PATH"	VARCHAR,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("DEVICE_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "BUDGET" (
	"ID"	integer,
	"uid"	TEXT,
	"targetUid"	TEXT,
	"DO_TYPE"	integer,
	"PERIOD_TYPE"	integer,
	"IS_TOTAL"	integer,
	"IS_DEL"	integer,
	"TRANSFER_TYPE"	integer,
	"ORDER_SEQ"	integer,
	"MODIFY_DATE"	integer,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "BUDGET_AMOUNT" (
	"ID"	integer,
	"uid"	text,
	"budgetUid"	TEXT,
	"IS_DEL"	integer,
	"AMOUNT"	real,
	"BUDGET_PERIOD"	integer,
	"MODIFY_DATE"	integer,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CURRENCY" (
	"ID"	integer,
	"uid"	varchar,
	"NAME"	varchar,
	"ISO"	varchar,
	"MAIN_ISO"	varchar,
	"IS_DEL"	integer,
	"ORDER_SEQ"	integer,
	"RATE"	real,
	"SYMBOL"	varchar,
	"INSERT_TYPE"	varchar,
	"SYMBOL_POSITION"	varchar,
	"IS_MAIN_CURRENCY"	integer,
	"IS_SHOW"	integer,
	"MODIFY_DATE"	integer,
	"DECIMAL_POINT"	integer,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "MEMO" (
	"id"	integer,
	"uid"	text,
	"title"	text,
	"content"	text,
	"memoTime"	real,
	"memoDate"	text,
	"pinned"	integer,
	"pinnedTime"	real,
	"orderSeq"	integer,
	"color"	text,
	"isDel"	integer,
	"utime"	real,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TAG" (
	"id"	integer,
	"uid"	text,
	"name"	text,
	"orderSeq"	integer,
	"isDel"	integer,
	"utime"	real,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TX_TAG" (
	"id"	integer,
	"uid"	text,
	"txUid"	text,
	"tagUid"	text,
	"objName"	text,
	"orderSeq"	integer,
	"isDel"	integer,
	"utime"	real,
	"isSynced"	integer,
	"syncTime"	real,
	"syncVersion"	integer,
	PRIMARY KEY("id" AUTOINCREMENT)
);